### ISSUE TITLE
14.3.dbr fun

### ISSUE THREAD

**Issue by chris-twiner** [sparkutils/shim#3]
from quality tests using frameless with shim on staticinvoke

```

25) testSimpleProductionRulesReplaceDebugSet(com.sparkutils.qualityTests.RuleFolderTest)
java.lang.NoSuchMethodError: org.apache.spark.sql.catalyst.analysis.UnresolvedFunction.copy(Lscala/collection/Seq;Lscala/collection/Seq;ZLscala/Option;Z)Lorg/apache/spark/sql/catalyst/analysis/UnresolvedFunction;
	at org.apache.spark.sql.ShimUtils$UnresolvedFunctionOps.withArguments(ShimUtils.scala:60)
	at com.sparkutils.quality.impl.UpdateFolderExpression$.withArgsAndSubstitutedLambdaVariable(RuleImpl.scala:299)
```

**Comment by chris-twiner** [comment]
tested on Quality - all 410 pass
